-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXAZVVme1gWKHzSV+
NZspQpkN0tfCFCGQxkU+u6E8nj2gCgYIKoZIzj0DAQehRANCAAQSnzPVVfMvcRCr
2XG26XGgHZMdelZRnA80ClGNcnvIelYnf5MkHtb8V3FPZ5r06fzdIF2axdPoQWzJ
ObJeX5eb
-----END PRIVATE KEY-----